"""first migration

Revision ID: 2bae8e2c7bcd
Revises: 
Create Date: 2024-03-12 20:43:10.299009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bae8e2c7bcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('assigned', sa.String(length=128), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('group', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('chore')
    # ### end Alembic commands ###
