"""added lifetime chorecount

Revision ID: 50dfa55d67f4
Revises: f910e262fd5a
Create Date: 2024-03-12 23:43:14.462844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50dfa55d67f4'
down_revision = 'f910e262fd5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choreCount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('choreCount')

    # ### end Alembic commands ###
