"""Initial migration.

Revision ID: 8f53cdd5ae6b
Revises: 
Create Date: 2024-03-12 18:46:28.514117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f53cdd5ae6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chore',
    sa.Column('group', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('assigned', sa.String(length=128), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('group', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('chore')
    # ### end Alembic commands ###
